//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentFeeCalculator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.95")]
        public decimal PaypalPorciento {
            get {
                return ((decimal)(this["PaypalPorciento"]));
            }
            set {
                this["PaypalPorciento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal PaypalFija {
            get {
                return ((decimal)(this["PaypalFija"]));
            }
            set {
                this["PaypalFija"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public decimal Paypal3MSI {
            get {
                return ((decimal)(this["Paypal3MSI"]));
            }
            set {
                this["Paypal3MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.25")]
        public decimal Paypal6MSI {
            get {
                return ((decimal)(this["Paypal6MSI"]));
            }
            set {
                this["Paypal6MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.25")]
        public decimal Paypal9MSI {
            get {
                return ((decimal)(this["Paypal9MSI"]));
            }
            set {
                this["Paypal9MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13.5")]
        public decimal Paypal12MSI {
            get {
                return ((decimal)(this["Paypal12MSI"]));
            }
            set {
                this["Paypal12MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.6")]
        public decimal SenorPorciento {
            get {
                return ((decimal)(this["SenorPorciento"]));
            }
            set {
                this["SenorPorciento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal SenorFija {
            get {
                return ((decimal)(this["SenorFija"]));
            }
            set {
                this["SenorFija"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal Senor3MSI {
            get {
                return ((decimal)(this["Senor3MSI"]));
            }
            set {
                this["Senor3MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal Senor6MSI {
            get {
                return ((decimal)(this["Senor6MSI"]));
            }
            set {
                this["Senor6MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public decimal Senor9MSI {
            get {
                return ((decimal)(this["Senor9MSI"]));
            }
            set {
                this["Senor9MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public decimal Senor12MSI {
            get {
                return ((decimal)(this["Senor12MSI"]));
            }
            set {
                this["Senor12MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17.5")]
        public decimal MercadolibrePorciento {
            get {
                return ((decimal)(this["MercadolibrePorciento"]));
            }
            set {
                this["MercadolibrePorciento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.19")]
        public decimal MercadopagoPorciento {
            get {
                return ((decimal)(this["MercadopagoPorciento"]));
            }
            set {
                this["MercadopagoPorciento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public decimal MercadopagoFija {
            get {
                return ((decimal)(this["MercadopagoFija"]));
            }
            set {
                this["MercadopagoFija"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.97")]
        public decimal Mercadopago3MSI {
            get {
                return ((decimal)(this["Mercadopago3MSI"]));
            }
            set {
                this["Mercadopago3MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6.47")]
        public decimal Mercadopago6MSI {
            get {
                return ((decimal)(this["Mercadopago6MSI"]));
            }
            set {
                this["Mercadopago6MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.24")]
        public decimal Mercadopago9MSI {
            get {
                return ((decimal)(this["Mercadopago9MSI"]));
            }
            set {
                this["Mercadopago9MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.31")]
        public decimal Mercadopago12MSI {
            get {
                return ((decimal)(this["Mercadopago12MSI"]));
            }
            set {
                this["Mercadopago12MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.6")]
        public decimal ClipPorciento {
            get {
                return ((decimal)(this["ClipPorciento"]));
            }
            set {
                this["ClipPorciento"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ClipFija {
            get {
                return ((decimal)(this["ClipFija"]));
            }
            set {
                this["ClipFija"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4.5")]
        public decimal Clip3MSI {
            get {
                return ((decimal)(this["Clip3MSI"]));
            }
            set {
                this["Clip3MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7.5")]
        public decimal Clip6MSI {
            get {
                return ((decimal)(this["Clip6MSI"]));
            }
            set {
                this["Clip6MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.9")]
        public decimal Clip9MSI {
            get {
                return ((decimal)(this["Clip9MSI"]));
            }
            set {
                this["Clip9MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11.95")]
        public decimal Clip12MSI {
            get {
                return ((decimal)(this["Clip12MSI"]));
            }
            set {
                this["Clip12MSI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public decimal TasaIVA {
            get {
                return ((decimal)(this["TasaIVA"]));
            }
            set {
                this["TasaIVA"] = value;
            }
        }
    }
}
